name: "tagged-release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update version.go
        run: |
          sed -i 's/const version = ".*"/const version = "${{ github.event.inputs.version }}"/' cmd/version.go
          
      - name: Commit version bump
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cmd/version.go
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git push
          
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Test
        run: go build -v && go test ./...
      - name: Build for linux/amd64
        run: go build -o terraformer-all-linux-amd64
      - name: Build for linux/arm64
        run: GOOS=linux GOARCH=arm64 go build -o terraformer-all-linux-arm64
      - name: Build for mac
        run: GOOS=darwin go build -o terraformer-all-darwin-amd64
      - name: Build for mac Apple Silicon
        run: GOOS=darwin GOARCH=arm64 go build -o terraformer-all-darwin-arm64
      - name: Build for all providers
        run: go run build/multi-build/main.go

      - name: Create Release
        uses: darioblanco/release-wizard@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          pushTag: true
          releaseTag: ${{ github.event.inputs.version }}
          templatePath: release-template.md

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: terraformer-*
          token: ${{ secrets.GITHUB_TOKEN }}
