name: Release Draft

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: darioblanco/release-wizard@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          templatePath: release-template.md 